### ISSUE TITLE
Console route is not accessible on libvirt

### ISSUE THREAD

**Issue by RobertKrawitz** [openshift/cluster-api-provider-libvirt#100]
After standing up a libvirt cluster using
```/home/rkrawitz/go/src/github.com/openshift/installer/bin/openshift-install v0.5.0-master-36-gb4f5ceb6bfde8d3dc0e29f708e0494488ea37ee0
ostree 47.191
Installer b4f5ceb6bfde8d3dc0e29f708e0494488ea37ee0
```
I can get the console route:
```oc get route -n openshift-console --no-headers=true |awk '{print $2}'
console-openshift-console.apps.dev1.rlk.home
```
but I get "can't find the server at ..." from my browser.  Same works for AWS.

**Comment by wking** [comment]
Cross-ref openshift/installer#411

**Comment by jasonbrooks** [comment]
I'm experiencing this too -- any workarounds?

**Comment by karmab** [comment]
@jasonbrooks 
as per the other thread

To access the console from libvirt, execute the following steps:

Allow kubectl to bind to privileged ports:

$ sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/kubectl
Note: If you omit the above, you have to start kubectl using sudo. Next, port-forward the router-default service:

$  kubectl -n openshift-ingress port-forward svc/router-default 443
Get the routes and add bind them to 127.0.0.1 in /etc/hosts:

$ kubectl get routes --all-namespaces 
NAMESPACE              NAME             HOST/PORT                                                   PATH   SERVICES         PORT    TERMINATION          WILDCARD
openshift-console      console          console-openshift-console.apps.test1.tt.testing                    console          https   reencrypt/Redirect   None
openshift-monitoring   grafana          grafana-openshift-monitoring.apps.test1.tt.testing                 grafana          https   reencrypt            None
openshift-monitoring   prometheus-k8s   prometheus-k8s-openshift-monitoring.apps.test1.tt.testing          prometheus-k8s   web     reencrypt            None

$ cat /etc/hosts
127.0.0.1 console-openshift-console.apps.test1.tt.testing           
127.0.0.1 grafana-openshift-monitoring.apps.test1.tt.testing        
127.0.0.1 prometheus-k8s-openshift-monitoring.apps.test1.tt.testing 
Use the credentials as described in #411 (comment)

Open i.e. https://grafana-openshift-monitoring.apps.test1.tt.testing or https://console-openshift-console.apps.test1.tt.testing.
