### ISSUE TITLE
Support 'host-passthrough' CPU type (and generally, CPU type) for worker nodes

### ISSUE THREAD

**Issue by mykaul** [openshift/cluster-api-provider-libvirt#105]
Currently, the VMs are created with the default CPU type of libvirt. If we could define the CPU type, it'd be great - it'll allow us to use 'host-passthrough' CPU type.

**Comment by tareqalayan** [comment]
This issue also affects kubevirt. When trying to install openshift on libvirt as providers: the VM which will act as workers should be created with CPU mode  either “host-model” or “host-passthrough”.
So a VM can run inside the worker.

**Comment by fabiand** [comment]
@cynepco3hahue any idea if we can fix this?

**Comment by cynepco3hahue** [comment]
I think we just need to provide `host-passthrough` to the definition of VM, I do not see the reason to make it customizable.

**Comment by mykaul** [comment]
Last time I've tried, at least the bootstrap and the master were OK. Perhaps it's just the workers?

**Comment by cynepco3hahue** [comment]
@mykaul Yep it just workers, because master and bootstrap created via terraform plugin and workers created via machine API.

**Comment by pavolbrilla** [comment]
Instead of 'host-passthrough' could we please go by better abstract 'host-model' - which is solving issues with spectre for example?

**Comment by zeenix** [comment]
I'm not sure how relevant this information is in this context but back in the days I recall having quite some issues with `host-passthrough` in GNOME Boxes and we ended up with: https://gitlab.gnome.org/GNOME/gnome-boxes/commit/36c2f960ec00b0414e1c774eeefa497d2dfd4a86 . The commit message provides a lot of context (as it always should).

**Comment by fabiand** [comment]
I only was referring to host passthrough semantically. Technically it
should be host-model (in the libvirt terms). No question :)
Sorry for the confusion.

**Comment by cynepco3hahue** [comment]
@pavolbrilla I do not sure how `host-model` solves specter or meltdown problem, IIRC you need to specify custom CPU models that end with `*-IBRS` and `host-model` will try just to apply CPU model the most closed to the host one and at least performance of ` host-passthrough` should be better than `host-model`. But in general, I do not have a problem to set `host-model`, can you please confirm that it solves the issues with nested virtualization?

**Comment by mykaul** [comment]
@zeenix - I'm reading the opposite - if we use KVM virt (and not just QEMU), we should prefer host-passthrough.
From experience (running nested virt CI tests for years with https://github.com/lago-project/lago ), it worked quite well for us.

**Comment by zeenix** [comment]
@mykaul Compared to `host-model`, `host-passthrough` is definitely more reliable but in our testing, the most reliable has been `custom` with CPU set from the capabilites reported by libvirt. If done right, this would translate to the same as `host-passthrough` in most cases but it's more fault-proof.
