### ISSUE TITLE
Link in README leads to 404

### ISSUE THREAD

**Issue by mykaul** [openshift/cluster-api-provider-libvirt#106]
The link here:
```
Before running the installer make sure you set libvirt to use the host private ip uri above: https://github.com/openshift/installer/blob/master/examples/tectonic.libvirt.yaml#L14
```

leads to 404.

**Comment by cfergeau** [comment]
I believe this link was pointing at
```
  # You must specify an IP address here that libvirtd is listening on,
  # and that the cluster-api controller pod will be able to connect
  # to.  Often 192.168.122.1 is the default for the virbr0 interface.
  uri: qemu+tcp://192.168.122.1/system
```
so this is basically saying to make sure that your system is configured as described in https://github.com/openshift/installer/tree/master/docs/dev/libvirt before running the installer.

**Comment by cfergeau** [comment]
Still an issue, hopefully I'll be able to push #208 relatively soon. This PR fixes this issue.
