### ISSUE TITLE
libvirt pool path is wrong when it is not default

### ISSUE THREAD

**Issue by Jooho** [openshift/cluster-api-provider-libvirt#108]
Even though I use custom path for storagePool(/home/jooho/KVM), the actuator try to use wrong path.

~~~
E0112 03:54:03.202553       1 actuator.go:107] Machine error: error creating volume Can't retrieve volume /var/lib/libvirt/images/tbd-base
E0112 03:54:03.203245       1 actuator.go:51] tbd/tbd-worker-0-nhzvf: error creating libvirt machine: error creating volume Can't retrieve volume /var/lib/libvirt/images/tbd-base
E0112 03:54:04.259706       1 actuator.go:107] Machine error: error creating volume Can't retrieve volume /var/lib/libvirt/images/tbd-base
E0112 03:54:04.259734       1 actuator.go:51] tbd/tbd-worker-0-d554w: error creating libvirt machine: error creating volume Can't retrieve volume /var/lib/libvirt/images/tbd-base
~~~

The worker storage files are generated under `/home/jooho/KVM` but it failed to retrieve the files because it tried to load them under `/var/lib/libvirt/images`. 

## Expected result
it should search right path where the image files are generated.

**Comment by wking** [comment]
#45 should fix this.

**Comment by cfergeau** [comment]
#45 was superseded by https://github.com/openshift/cluster-api-provider-libvirt/pull/144 which is merged, so hopefully this no longer is an issue?
