### ISSUE TITLE
scale machinesets no effect

### ISSUE THREAD

**Issue by jichenjc** [openshift/cluster-api-provider-libvirt#164]
oc scale --replicas=3 machineset test1-nf857-worker-0  -n openshift-machine-api

[core@test1-nf857-master-0 ~]$ oc get machinesets -n openshift-machine-api
NAME                   DESIRED   CURRENT   READY   AVAILABLE   AGE
test1-nf857-worker-0   3         3         1       1           24h

logs from:
oc logs machine-api-controllers-c59d8448c-644ns -n openshift-machine-api -c controller-manager

I0725 05:48:35.725479       1 controller.go:331] Creating machine 1 of 1, ( spec.replicas(2) > currentMachineCount(1) )
I0725 05:48:35.890195       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:48:35.956498       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:48:35.956819       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:48:55.052917       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:48:55.053447       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:48:56.723417       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:49:30.928201       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:49:31.044226       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster
I0725 05:49:32.162709       1 controller.go:298] MachineSet "test1-nf857-worker-0" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster

**Comment by jichenjc** [comment]
this is from installer openshift using libvirt, I think this will use provider-libvirt to do provisioning

**Comment by zeenix** [comment]
It takes a bit of time. I was able reproduce this issue exactly:

```
$ oc get machinesets -n openshift-machine-api
NAME                   DESIRED   CURRENT   READY   AVAILABLE   AGE
test1-cbp4l-worker-0   1         1         1       1           39m
$ oc scale --replicas=3 machineset test1-cbp4l-worker-0  -n openshift-machine-api
machineset.machine.openshift.io/test1-cbp4l-worker-0 scaled
$ oc get machinesets -n openshift-machine-api
NAME                   DESIRED   CURRENT   READY   AVAILABLE   AGE
test1-cbp4l-worker-0   3         3         1       1           40m
```

 but after a minute (your mileage may vary), the machines are fully fully ready:

```
$ oc get machinesets -n openshift-machine-api
NAME                   DESIRED   CURRENT   READY   AVAILABLE   AGE
test1-cbp4l-worker-0   3         3         3       3           45m
```

/close
