### ISSUE TITLE
RFE: Support for hugepages (2Mb, 1G, etc..) on libvirt

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/cluster-api-provider-libvirt#206]
Hi,

On my hypervisors (RHEL), I have most of the memory dedicated to hugepages (the default 2Mb hugepages).
This allows me to fit more VMs into reserved memory and makes their TLB's smaller (needed when you have 64Gb or more memory).

Here's an example:

```# virsh dumpxml sat6|head -24
<domain type='kvm' id='3'>
  <name>sat6</name>
[...]
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
[...]
```
(The above is for the default 2mb hugepages, for 1G hugepages the syntax is slightly different).

I've done some research and it appears that Terraform has support for hugepages but I wouldn't know where to change it in the openshift installer..
Do you have any idea of where that might be?
Any hint would be welcomed..

**Comment by cfergeau** [comment]
I think the terraform -> libvirt xml mapping is done in https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/resource_libvirt_domain.go but I see no references to `memoryBacking` or `hugepages` there so I'm not sure it supports huge pages.
